services:
    monolith-server:
        build: .
        container_name: monolith-server
        restart: unless-stopped
        environment:
            - TOKEN=${TOKEN}
        networks:
            - monolith-network
    monolith:
        build: ./web
        container_name: monolith
        restart: unless-stopped
        ports:
            - "8000:8000"
        networks:
            - monolith-network

networks:
    monolith-network:
        driver: bridge
